package com.example.ui

object Trans {
    private val locales = mapOf(
        "vi" to mapOf(
            "app_title" to "MomentLoop",
            "search_goal" to "Tìm kiếm hành trình...",
            "stats" to "Thống kê",
            "settings" to "Cài đặt & Thiết lập",
            "daily_reminder" to "Nhắc nhở hàng ngày",
            "reminder_desc" to "Nhận thông báo thúc đẩy lúc 20:00 hằng ngày cho hành trình thụt lùi",
            "language" to "Ngôn ngữ / Language",
            "lang_en" to "Tiếng Anh (English)",
            "lang_vi" to "Tiếng Việt",
            "done" to "Xong",
            "cancel" to "Huỷ",
            "create" to "Tạo",
            "new_journey" to "Hành trình mới",
            "journey_title" to "Tên hành trình (ví dụ: Gym, Code, Nấu ăn...)",
            "choose_theme" to "Chọn màu chủ đề",
            "choose_bg" to "Chọn ảnh nền của hành trình",
            "bg_preset" to "Chọn mẫu nền nghệ thuật",
            "preset_none" to "Mặc định (Không có)",
            "preset_fitness" to "Năng động Gym-Fit 🔥",
            "preset_productivity" to "Phòng làm việc Lofi 💻",
            "preset_cooking" to "Nhà bếp Cozy 🍳",
            "preset_spark" to "Dải Ngân Hà Lấp Lánh ✨",
            "preset_nature" to "Rừng Nhiệt Đới 🌱",
            "empty_state_title" to "Khởi đầu hành trình mới",
            "empty_state_desc" to "Nhấp vào nút bên dưới để khởi tạo mục tiêu của bạn (ví dụ: Luyện tập, Lập trình, Đọc sách...)",
            "empty_state_btn" to "Tạo hành trình ngay",
            "progress" to "Tiến trình",
            "streak" to "Duy trì",
            "decay_warn" to "đang nhớ bạn đấy 👀 — hãy tiếp tục nào!",
            "ai_coach" to "AI Coach",
            "score" to "Điểm",
            "camera_nudge" to "MomentLoop cần quyền sử dụng máy ảnh để ghi lại nỗ lực.",
            "camera_grant" to "Cấp quyền",
            "use_placeholder" to "Dùng ảnh mô phỏng 🚀",
            "send_to_loop" to "Gửi vào Loop",
            "saving" to "Đang lưu...",
            "analyzing" to "AI đang phân tích và nhận xét nỗ lực của bạn... 🤖",
            "retake" to "Chụp lại",
            "goal_reached" to "Mục tiêu: vươn tới 100%",
            "overall_progress" to "Tiến độ đạt được",
            "streak_days" to "Duy trì liên tục: {count} ngày! 🔥",
            "cineloop_btn" to "CineLoop Slideshow 🎬",
            "cineloop_title" to "Moment CineLoop",
            "unlocked" to "Đã mở khoá",
            "cineloop_desc" to "Trình chiếu các nỗ lực ở chế độ Phim Điện Ảnh cực kì nghệ thuật kết hợp nhạc lofi!",
            "delete_journey" to "Xoá hành trình",
            "back" to "Quay lại",
            "save" to "Lưu",
            "save_changes" to "Sửa ghi chú của bạn:",
            "add_first_moment" to "Chạm vào máy ảnh bên dưới để ghi lại khoảnh khắc nỗ lực đầu tiên ngày hôm nay!",
            "date_format" to "dd/MM/yyyy HH:mm",
            "streak_card" to "🔥 {count} ngày liên tục",
            "oracle_msg" to "Gợi ý động lực: ",
            "oracle_btn" to "Motivation Oracle ✨",
            "cineloop_instructions" to "Các khoảnh khắc đang trôi qua của bạn. Vuốt ngang hoặc nhấn các nút để đổi chế độ lọc màu!",
            "music_mood" to "Giai điệu: ",
            "color_filter" to "Bộ lọc màu: ",
            "playback_speed" to "Tốc độ chạy: ",
            "recent_photo" to "Ảnh gần đây bên ngoài: ",
            "latest_moment_preview" to "Khoảnh khắc mới nhất",
            "export_title" to "Xuất hành trình",
            "export_slide_story" to "Chia sẻ Slide Story (HTML)",
            "export_slide_story_desc" to "Tạo trang câu chuyện ảnh cuộn mượt tự chứa đầy đủ để chia sẻ",
            "export_summary_text" to "Sao chép tóm tắt dạng chữ",
            "export_summary_text_desc" to "Sao chép danh sách khoảnh khắc đã chuyển đổi thành văn bản vào khay nhớ tạm",
            "copied_toast" to "Đã sao chép tóm tắt hành trình vào bộ nhớ tạm! 🎉",
            "export_error" to "Lỗi xảy ra khi xuất câu chuyện hành trình!",
            "export_not_enough_moments" to "Hành trình cần ít nhất 1 khoảnh khắc để xuất câu chuyện!",
            "widget_time_settings" to "Giờ hiển thị trên Widget",
            "widget_time_desc" to "Chọn khoảng giờ (0h-23h) trong ngày để hiển thị dự án tương ứng trên Widget.",
            "start_hour" to "Bắt đầu lúc (H)",
            "end_hour" to "Kết thúc lúc (H)",
            "edit_journey" to "Chỉnh sửa hành trình",
            "journey_title_edit" to "Tên hành trình"
        ),
        "en" to mapOf(
            "app_title" to "MomentLoop",
            "search_goal" to "Search journeys...",
            "stats" to "Statistics",
            "settings" to "Preferences",
            "daily_reminder" to "Daily Reminders",
            "reminder_desc" to "Get motivating reminders at 20:00 every day for decaying journeys",
            "language" to "Language / Ngôn ngữ",
            "lang_en" to "English",
            "lang_vi" to "Vietnamese (Tiếng Việt)",
            "done" to "Done",
            "cancel" to "Cancel",
            "create" to "Create",
            "new_journey" to "New Journey",
            "journey_title" to "Journey name (e.g. Gym, Coding, Cooking...)",
            "choose_theme" to "Choose theme color",
            "choose_bg" to "Choose background style",
            "bg_preset" to "Choose Artistic Pattern",
            "preset_none" to "Default (None)",
            "preset_fitness" to "Energetic Gym-Fit 🔥",
            "preset_productivity" to "Lofi Workspace 💻",
            "preset_cooking" to "Cozy Kitchen 🍳",
            "preset_spark" to "Sparkling Cosmic Dust ✨",
            "preset_nature" to "Tropical Forest 🌱",
            "empty_state_title" to "Start a new journey",
            "empty_state_desc" to "Tap the button below to initialize your goal (e.g., Fitness, Coding, Reading...)",
            "empty_state_btn" to "Create journey now",
            "progress" to "Progress",
            "streak" to "Streak",
            "decay_warn" to "misses you 👀 — keep going!",
            "ai_coach" to "AI Coach",
            "score" to "Score",
            "camera_nudge" to "MomentLoop needs camera permissions to capture and record your effort.",
            "camera_grant" to "Grant Permission",
            "use_placeholder" to "Use Simulated Photo 🚀",
            "send_to_loop" to "Send to Loop",
            "saving" to "Saving...",
            "analyzing" to "AI is analyzing and evaluating your effort... 🤖",
            "retake" to "Retake",
            "goal_reached" to "Goal: reach 100%",
            "overall_progress" to "Overall Progress",
            "streak_days" to "Continuous Streak: {count} days! 🔥",
            "cineloop_btn" to "CineLoop Slideshow 🎬",
            "cineloop_title" to "Moment CineLoop",
            "unlocked" to "Unlocked",
            "cineloop_desc" to "Immersive, cinematic movie reel of your progress synced with lo-fi beats!",
            "delete_journey" to "Delete Journey",
            "back" to "Back",
            "save" to "Save",
            "save_changes" to "Edit your notes:",
            "add_first_moment" to "Tap the camera below to record your first daily moment!",
            "date_format" to "yyyy/MM/dd HH:mm",
            "streak_card" to "🔥 {count} day streak",
            "oracle_msg" to "Motivator check: ",
            "oracle_btn" to "Motivation Oracle ✨",
            "cineloop_instructions" to "Your journey moments passing by. Swipe horizontally or tap filters below to style your playback!",
            "music_mood" to "Soundtrack: ",
            "color_filter" to "Color Filter: ",
            "playback_speed" to "Speed: ",
            "recent_photo" to "Recent display: ",
            "latest_moment_preview" to "Latest Moment",
            "export_title" to "Export Journey",
            "export_slide_story" to "Share as Slide Story (HTML)",
            "export_slide_story_desc" to "Generate a self-contained beautiful scroll-snap HTML page of your journey",
            "export_summary_text" to "Copy Text Summary",
            "export_summary_text_desc" to "Copy formatted chronological text of your efforts to clipboard",
            "copied_toast" to "Journey summary copied to clipboard! 🎉",
            "export_error" to "Failed to generate HTML Export!",
            "export_not_enough_moments" to "Add at least 1 moment to export your timeline!",
            "widget_time_settings" to "Widget Display Hours",
            "widget_time_desc" to "Configure the hour range (0h-23h) of the day this project should show up on your Home Widget.",
            "start_hour" to "Start Hour (H)",
            "end_hour" to "End Hour (H)",
            "edit_journey" to "Edit Journey Settings",
            "journey_title_edit" to "Journey Title"
        )
    )

    fun t(key: String, lang: String): String {
        return locales[lang]?.get(key) ?: locales["vi"]?.get(key) ?: key
    }
}
